name: page_viewer
description: App can fetch posts and display each one on separate page.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter

  # DI
  get_it: ^7.2.0
  injectable: ^1.5.3
  provider: ^6.0.2
  # DB
  sembast: ^3.1.2
  # REST API
  http: ^0.13.4
  retrofit: ^3.0.1+1
  # UI
  cupertino_icons: ^1.0.2
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
